# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw32\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw32\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\toch\Desktop\OpenGL\exercises

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\toch\Desktop\OpenGL\exercises

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	C:\msys64\mingw32\bin\ctest.exe --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	C:\msys64\mingw32\bin\cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	C:\msys64\mingw32\bin\cpack.exe --config ./CPackSourceConfig.cmake C:/Users/toch/Desktop/OpenGL/exercises/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw32\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\msys64\mingw32\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\toch\Desktop\OpenGL\exercises\CMakeFiles C:\Users\toch\Desktop\OpenGL\exercises\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\toch\Desktop\OpenGL\exercises\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles\ContinuousSubmit.dir\build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles\ContinuousBuild.dir\build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles\ExperimentalSubmit.dir\build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles\ContinuousStart.dir\build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles\ExperimentalMemCheck.dir\build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles\ExperimentalCoverage.dir\build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles\Experimental.dir\build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles\NightlyMemoryCheck.dir\build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles\NightlyCoverage.dir\build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles\ContinuousMemCheck.dir\build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles\ExperimentalBuild.dir\build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles\NightlyUpdate.dir\build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles\ContinuousUpdate.dir\build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles\Continuous.dir\build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles\NightlyConfigure.dir\build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles\NightlyBuild.dir\build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles\Nightly.dir\build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles\ContinuousCoverage.dir\build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles\NightlyStart.dir\build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles\NightlyTest.dir\build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles\ExperimentalStart.dir\build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named One_Triangle

# Build rule for target.
One_Triangle: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 One_Triangle
.PHONY : One_Triangle

# fast build rule for target.
One_Triangle/fast:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/build
.PHONY : One_Triangle/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles\ContinuousTest.dir\build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles\ContinuousConfigure.dir\build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles\NightlyMemCheck.dir\build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles\ExperimentalTest.dir\build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles\NightlySubmit.dir\build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles\ExperimentalUpdate.dir\build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles\ExperimentalConfigure.dir\build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/main.cpp.s
.PHONY : main.cpp.s

src/DisplayMenager.obj: src/DisplayMenager.cpp.obj

.PHONY : src/DisplayMenager.obj

# target to build an object file
src/DisplayMenager.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/DisplayMenager.cpp.obj
.PHONY : src/DisplayMenager.cpp.obj

src/DisplayMenager.i: src/DisplayMenager.cpp.i

.PHONY : src/DisplayMenager.i

# target to preprocess a source file
src/DisplayMenager.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/DisplayMenager.cpp.i
.PHONY : src/DisplayMenager.cpp.i

src/DisplayMenager.s: src/DisplayMenager.cpp.s

.PHONY : src/DisplayMenager.s

# target to generate assembly for a file
src/DisplayMenager.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/DisplayMenager.cpp.s
.PHONY : src/DisplayMenager.cpp.s

src/IndexBuffer.obj: src/IndexBuffer.cpp.obj

.PHONY : src/IndexBuffer.obj

# target to build an object file
src/IndexBuffer.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/IndexBuffer.cpp.obj
.PHONY : src/IndexBuffer.cpp.obj

src/IndexBuffer.i: src/IndexBuffer.cpp.i

.PHONY : src/IndexBuffer.i

# target to preprocess a source file
src/IndexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/IndexBuffer.cpp.i
.PHONY : src/IndexBuffer.cpp.i

src/IndexBuffer.s: src/IndexBuffer.cpp.s

.PHONY : src/IndexBuffer.s

# target to generate assembly for a file
src/IndexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/IndexBuffer.cpp.s
.PHONY : src/IndexBuffer.cpp.s

src/Loader.obj: src/Loader.cpp.obj

.PHONY : src/Loader.obj

# target to build an object file
src/Loader.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Loader.cpp.obj
.PHONY : src/Loader.cpp.obj

src/Loader.i: src/Loader.cpp.i

.PHONY : src/Loader.i

# target to preprocess a source file
src/Loader.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Loader.cpp.i
.PHONY : src/Loader.cpp.i

src/Loader.s: src/Loader.cpp.s

.PHONY : src/Loader.s

# target to generate assembly for a file
src/Loader.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Loader.cpp.s
.PHONY : src/Loader.cpp.s

src/RawModel.obj: src/RawModel.cpp.obj

.PHONY : src/RawModel.obj

# target to build an object file
src/RawModel.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/RawModel.cpp.obj
.PHONY : src/RawModel.cpp.obj

src/RawModel.i: src/RawModel.cpp.i

.PHONY : src/RawModel.i

# target to preprocess a source file
src/RawModel.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/RawModel.cpp.i
.PHONY : src/RawModel.cpp.i

src/RawModel.s: src/RawModel.cpp.s

.PHONY : src/RawModel.s

# target to generate assembly for a file
src/RawModel.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/RawModel.cpp.s
.PHONY : src/RawModel.cpp.s

src/Renderer.obj: src/Renderer.cpp.obj

.PHONY : src/Renderer.obj

# target to build an object file
src/Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Renderer.cpp.obj
.PHONY : src/Renderer.cpp.obj

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Shader.obj: src/Shader.cpp.obj

.PHONY : src/Shader.obj

# target to build an object file
src/Shader.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Shader.cpp.obj
.PHONY : src/Shader.cpp.obj

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Test.obj: src/Test.cpp.obj

.PHONY : src/Test.obj

# target to build an object file
src/Test.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Test.cpp.obj
.PHONY : src/Test.cpp.obj

src/Test.i: src/Test.cpp.i

.PHONY : src/Test.i

# target to preprocess a source file
src/Test.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Test.cpp.i
.PHONY : src/Test.cpp.i

src/Test.s: src/Test.cpp.s

.PHONY : src/Test.s

# target to generate assembly for a file
src/Test.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/Test.cpp.s
.PHONY : src/Test.cpp.s

src/VertexArray.obj: src/VertexArray.cpp.obj

.PHONY : src/VertexArray.obj

# target to build an object file
src/VertexArray.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexArray.cpp.obj
.PHONY : src/VertexArray.cpp.obj

src/VertexArray.i: src/VertexArray.cpp.i

.PHONY : src/VertexArray.i

# target to preprocess a source file
src/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexArray.cpp.i
.PHONY : src/VertexArray.cpp.i

src/VertexArray.s: src/VertexArray.cpp.s

.PHONY : src/VertexArray.s

# target to generate assembly for a file
src/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexArray.cpp.s
.PHONY : src/VertexArray.cpp.s

src/VertexBuffer.obj: src/VertexBuffer.cpp.obj

.PHONY : src/VertexBuffer.obj

# target to build an object file
src/VertexBuffer.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexBuffer.cpp.obj
.PHONY : src/VertexBuffer.cpp.obj

src/VertexBuffer.i: src/VertexBuffer.cpp.i

.PHONY : src/VertexBuffer.i

# target to preprocess a source file
src/VertexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexBuffer.cpp.i
.PHONY : src/VertexBuffer.cpp.i

src/VertexBuffer.s: src/VertexBuffer.cpp.s

.PHONY : src/VertexBuffer.s

# target to generate assembly for a file
src/VertexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexBuffer.cpp.s
.PHONY : src/VertexBuffer.cpp.s

src/VertexBufferLayout.obj: src/VertexBufferLayout.cpp.obj

.PHONY : src/VertexBufferLayout.obj

# target to build an object file
src/VertexBufferLayout.cpp.obj:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexBufferLayout.cpp.obj
.PHONY : src/VertexBufferLayout.cpp.obj

src/VertexBufferLayout.i: src/VertexBufferLayout.cpp.i

.PHONY : src/VertexBufferLayout.i

# target to preprocess a source file
src/VertexBufferLayout.cpp.i:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexBufferLayout.cpp.i
.PHONY : src/VertexBufferLayout.cpp.i

src/VertexBufferLayout.s: src/VertexBufferLayout.cpp.s

.PHONY : src/VertexBufferLayout.s

# target to generate assembly for a file
src/VertexBufferLayout.cpp.s:
	$(MAKE) -f CMakeFiles\One_Triangle.dir\build.make CMakeFiles/One_Triangle.dir/src/VertexBufferLayout.cpp.s
.PHONY : src/VertexBufferLayout.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... test
	@echo ... package
	@echo ... ContinuousSubmit
	@echo ... ContinuousBuild
	@echo ... ExperimentalSubmit
	@echo ... ContinuousStart
	@echo ... ExperimentalMemCheck
	@echo ... ExperimentalCoverage
	@echo ... Experimental
	@echo ... package_source
	@echo ... NightlyMemoryCheck
	@echo ... NightlyCoverage
	@echo ... ContinuousMemCheck
	@echo ... ExperimentalBuild
	@echo ... NightlyUpdate
	@echo ... ContinuousUpdate
	@echo ... Continuous
	@echo ... rebuild_cache
	@echo ... NightlyConfigure
	@echo ... NightlyBuild
	@echo ... Nightly
	@echo ... ContinuousCoverage
	@echo ... NightlyStart
	@echo ... NightlyTest
	@echo ... ExperimentalStart
	@echo ... One_Triangle
	@echo ... ContinuousTest
	@echo ... ContinuousConfigure
	@echo ... NightlyMemCheck
	@echo ... ExperimentalTest
	@echo ... NightlySubmit
	@echo ... edit_cache
	@echo ... ExperimentalUpdate
	@echo ... ExperimentalConfigure
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... src/DisplayMenager.obj
	@echo ... src/DisplayMenager.i
	@echo ... src/DisplayMenager.s
	@echo ... src/IndexBuffer.obj
	@echo ... src/IndexBuffer.i
	@echo ... src/IndexBuffer.s
	@echo ... src/Loader.obj
	@echo ... src/Loader.i
	@echo ... src/Loader.s
	@echo ... src/RawModel.obj
	@echo ... src/RawModel.i
	@echo ... src/RawModel.s
	@echo ... src/Renderer.obj
	@echo ... src/Renderer.i
	@echo ... src/Renderer.s
	@echo ... src/Shader.obj
	@echo ... src/Shader.i
	@echo ... src/Shader.s
	@echo ... src/Test.obj
	@echo ... src/Test.i
	@echo ... src/Test.s
	@echo ... src/VertexArray.obj
	@echo ... src/VertexArray.i
	@echo ... src/VertexArray.s
	@echo ... src/VertexBuffer.obj
	@echo ... src/VertexBuffer.i
	@echo ... src/VertexBuffer.s
	@echo ... src/VertexBufferLayout.obj
	@echo ... src/VertexBufferLayout.i
	@echo ... src/VertexBufferLayout.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

